apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: staging
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-deployment
          image: gcr.io/fleet-geode-253715/frontend-thoughtworks:1.2
          env:
          - name: "APP_PORT"
            value: "8082"
          - name: "STATIC_URL"
            value: "http://34.102.233.36"
          - name: "QUOTE_SERVICE_URL"
            value: "http://quotes-services.staging.svc.cluster.local:8080"
          - name: "NEWSFEED_SERVICE_URL"
            value: "http://newsfeed-services.staging.svc.cluster.local:8081"
          - name: "NEWSFEED_SERVICE_TOKEN"
            valueFrom:
              secretKeyRef:
                name: newsfeed-secrets
                key: tokenNewsfeed
          ports:
            - containerPort: 8082