kind: Service
apiVersion: v1
metadata:
  name: "quotes-services"
  namespace: "staging"
  labels:
    app: svc-quotes
spec:
  selector:
    app: "quotes"
  ports:
    - name: http 
      protocol: TCP
      port: 8080
  type: NodePort