kind: Service
apiVersion: v1
metadata:
  name: "newsfeed-services"
  namespace: "staging"
  labels:
    app: svc-newsfeed
spec:
  selector:
    app: "newsfeed"
  ports:
    - name: http 
      protocol: TCP
      port: 8081
  type: NodePort